sudo: required

compiler: gcc

env: COMPILER=g++-4.8

before_install:
    - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-add-repository -y ppa:beineri/opt-qt551-trusty
    - sudo apt-get -qq update
    - sudo apt-get -qq install $COMPILER libc6-i386 qt55tools qt55svg qt55webkit qt55serialport libboost-chrono1.48-dev libboost-system1.48-dev
    - export CXX=$COMPILER
    - PATH="/opt/qt55/bin:$PATH"
    - qt55-env.sh
    - mkdir -p build/.lib/
    - cd src

install:
    - wget 'https://s3-us-west-2.amazonaws.com/ucsolarteam.hostedfiles/astyle'
    - tar -zxvf astyle
    - (cd astyle/build/gcc && make release && sudo make install)
    - rm astyle -rf
    - git clone https://github.com/google/googletest.git
    - cd googletest
    - sudo cp -r googletest/include/gtest /usr/local/include
    - sudo cp -r googlemock/include/gmock /usr/local/include
    - g++ -isystem googletest/include/ -Igoogletest -isystem googlemock/include/ -Igooglemock -pthread -c googlemock/src/gmock-all.cc
    - g++ -isystem googletest/include/ -Igoogletest -isystem googlemock/include/ -Igooglemock -pthread -c googletest/src/gtest-all.cc
    - ar -rv libgmock.a gtest-all.o gmock-all.o
    - cp libgmock.a ../../build/.lib/
    - cd ..
    - git clone https://github.com/alanxz/rabbitmq-c
    - cd rabbitmq-c
    - sudo cp librabbitmq/*.h /usr/local/include/
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
    - sudo cp librabbitmq/librabbitmq.a /usr/local/lib/
    - sudo cp librabbitmq/*.so* /usr/local/lib/
    - cd ../..
    - git clone https://github.com/alanxz/SimpleAmqpClient
    - cd SimpleAmqpClient
    - mkdir build && cd build
    - cmake -DRabbitmqc_INCLUDE_DIR=../../rabbitmq-c/librabbitmq -DRabbitmqc_LIBRARY=../../rabbitmq-c/build/librabbitmq ..
    - make
    - sudo mkdir /usr/local/include/SimpleAmqpClient
    - sudo cp *.so* /usr/local/lib/
    - sudo cp ../src/SimpleAmqpClient/*.h /usr/local/include/SimpleAmqpClient/
    - cd ../..

script:
    - sudo mv /usr/bin/g++ /usr/bin/g++_depr
    - sudo ln -s $(which $CXX) /usr/bin/g++
    - $CXX --version
    - g++ --version
    - qmake
    - make
    - cd ..
    - "! (astyle *.h *.cpp -r --dry-run --options=astylerc --exclude=googletest | grep formatted)"
    # maybe not needed but still good practise
    - sudo mv /usr/bin/g++_depr /usr/bin/g++
    # execute the actual tests using xvfb to avoid problems with qt (QXcbConnection: Could not connect to display)
    - xvfb-run ./build/tests/runTestSuite 

language: cpp
