#pragma once

struct BatteryFaultsData
{
    BatteryFaultsData()
        : internalCommFault(true)
        , internalConversionFault(false)
        , weakCellFault(true)
        , lowCellVoltageFault(false)
        , openWiringFault(true)
        , currentSensorFault(false)
        , packVoltageSensorFault(true)
        , weakPackFault(false)
        , voltageRedundancyFault(true)
        , fanMonitorFault(false)
        , thermistorFault(true)
        , canbusCommsFault(false)
        , alwaysOnSupplyFault(true)
        , highVoltageIsolationFault(false)
        , powerSupplyFault(false)
        , chargeLimitFault(true)
        , dischargeLimitFault(false)
        , chargerSafetyRelayFault(true)
        , internalMemFault(false)
        , internalThermistorFault(false)
        , internalLogicFault(true)
        , dclReducedLowSoc(true)
        , dclReducedHighCellResist(false)
        , dclReducedDueToTemp(false)
        , dclReducedLowCellVoltage(true)
        , dclReducedLowPackVoltage(false)
        , dclCclReducedVoltageFailsafe(true)
        , dclCclReducedCommsFailsafe(false)
        , cclReducedHighSoc(true)
        , cclReducedHighCellResist(false)
        , cclReducedDueToTemp(true)
        , cclReducedHighCellVoltage(false)
        , cclReducedHighPackVoltage(true)
        , cclReducedChargerLatch(false)
        , cclReducedACLimit(true)
    {}

    bool internalCommFault;
    bool internalConversionFault;
    bool weakCellFault;
    bool lowCellVoltageFault;
    bool openWiringFault;
    bool currentSensorFault;
    bool packVoltageSensorFault;
    bool weakPackFault;
    bool voltageRedundancyFault;
    bool fanMonitorFault;
    bool thermistorFault;
    bool canbusCommsFault;
    bool alwaysOnSupplyFault;
    bool highVoltageIsolationFault;
    bool powerSupplyFault;
    bool chargeLimitFault;
    bool dischargeLimitFault;
    bool chargerSafetyRelayFault;
    bool internalMemFault;
    bool internalThermistorFault;
    bool internalLogicFault;

    bool dclReducedLowSoc;
    bool dclReducedHighCellResist;
    bool dclReducedDueToTemp;
    bool dclReducedLowCellVoltage;
    bool dclReducedLowPackVoltage;
    bool dclCclReducedVoltageFailsafe;
    bool dclCclReducedCommsFailsafe;
    bool cclReducedHighSoc;
    bool cclReducedHighCellResist;
    bool cclReducedDueToTemp;
    bool cclReducedHighCellVoltage;
    bool cclReducedHighPackVoltage;
    bool cclReducedChargerLatch;
    bool cclReducedACLimit;
};
